'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {DatabaseSync}=require('node:sqlite');
const {generated,searchGenerated}=require('../scripts/generate-schema');
const source=path.resolve(__dirname,'../src');
function fixture(){const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;CREATE TABLE tom_editor_documentos(id INTEGER PRIMARY KEY,revisao INTEGER NOT NULL,texto TEXT NOT NULL,documento TEXT NOT NULL,contexto TEXT NOT NULL DEFAULT '{}');`);for(const sql of fs.readFileSync(path.join(source,'esquema.sql'),'utf8').split('\n-- @statement\n'))db.exec(sql);
 db.function('tom_palavra_exata',(text,word)=>text.split(/[^\p{L}\p{M}\p{N}_'’]+/u).filter(x=>x===word).length);
 const ficha={titulo:'Poema antigo',incipit:'',corpus:'Fragmenta',genero:'Poema',subgenero:'',estado:'Rascunho',idioma:'pt',autor:'Felipe',persona:'',certeza:'Indeterminado',composicao:'2011',publicacao:'',tags:['pedra'],colecoes:['Ciclo'],notas:'',justificativa:'',arquivado:false};
 const id=Number(db.prepare('INSERT INTO textos DEFAULT VALUES').run().lastInsertRowid);
 const doc=text=>JSON.stringify({formato:'TomDocumento',versao:1,texto:text,estilos:[[Array.from(text).length,3072]],paragrafos:[[0,0]]});
 db.prepare('INSERT INTO tom_editor_documentos VALUES(?,1,?,?,?)').run(id,'',doc(''),'{}');
 function save(text,patch={},options={}){Object.assign(ficha,patch);const context={ficha,origem:0,motivo:'',fontes:[],...options};db.prepare('UPDATE tom_editor_documentos SET revisao=revisao+1,texto=?,documento=?,contexto=? WHERE id=?').run(text,doc(text),JSON.stringify(context),id);return db.prepare('SELECT * FROM acervo WHERE texto_id=?').get(id);}
 return {db,id,ficha,save,search:filters=>JSON.parse(db.prepare(fs.readFileSync(path.join(source,'pesquisa.sql'),'utf8')).get(JSON.stringify(filters))[Object.keys(db.prepare(fs.readFileSync(path.join(source,'pesquisa.sql'),'utf8')).get(JSON.stringify(filters)))[0]])};}
test('generated Tom matches the reviewed schema and search statements',()=>{assert.equal(fs.readFileSync(path.join(source,'esquema.tom'),'utf8'),generated());assert.equal(fs.readFileSync(path.join(source,'pesquisa.tom'),'utf8'),searchGenerated());});
test('historical authorship, immutable branches, metadata and current/history search',()=>{const {db,save,search}=fixture();try{
 const first=save('rocha coração');const second=save('rochas coracao',{persona:'Eric Lacques',certeza:'Provável',justificativa:'Reconhecido em 2026'});
 assert.equal(second.composicao,'2011');assert.equal(second.data_inicio,'2011-01-01');assert.equal(second.data_fim,'2011-12-31');assert.equal(second.pai_id,first.id);assert.equal(db.prepare('SELECT count(*) AS n FROM atribuicoes').get().n,2);
 assert.equal(search({busca:'rocha'}).total,0);assert.equal(search({busca:'rocha',historico:1}).total,1);assert.equal(search({busca:'coração'}).total,1);assert.equal(search({busca:'coração',exata:'1'}).total,0);
 assert.equal(search({persona:'Eric Lacques',inicio:'2010-01-01',fim:'2012-12-31',tag:'pedra',colecao:'Ciclo'}).total,1);
 const restored=save('rocha coração',{}, {origem:first.id,motivo:'Restauração'});assert.equal(restored.pai_id,first.id);assert.equal(db.prepare('SELECT count(*) AS n FROM versoes').get().n,3);
 assert.throws(()=>db.prepare('DELETE FROM versoes WHERE id=?').run(first.id),/apagadas/);assert.throws(()=>db.prepare('UPDATE versoes SET conteudo=? WHERE id=?').run('apagado',first.id),/imutáveis/);
 save('rocha coração',{arquivado:true});assert.equal(search({}).total,0);assert.equal(search({arquivados:1}).total,1);assert.equal(search({historico:1}).total,0);assert.equal(search({arquivados:1,historico:1}).total,4);assert.equal(db.prepare('SELECT count(*) AS n FROM versoes').get().n,4);
 }finally{db.close();}});
test('failed saves roll back document, metadata, provenance, FTS and history together',()=>{const {db,id,save,ficha}=fixture();try{save('memória');const before=db.prepare('SELECT * FROM tom_editor_documentos WHERE id=?').get(id);assert.throws(()=>save('perdido',{corpus:'Inválido'}));assert.deepEqual(db.prepare('SELECT * FROM tom_editor_documentos WHERE id=?').get(id),before);ficha.corpus='Fragmenta';assert.throws(()=>save('perdido',{}, {fontes:[{hash:'a'.repeat(64),inicio:0,fim:3}]}));assert.equal(db.prepare('SELECT count(*) AS n FROM versoes').get().n,1);assert.equal(db.prepare("SELECT count(*) AS n FROM pesquisa WHERE pesquisa MATCH 'perdido'").get().n,0);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');}finally{db.close();}});
test('partial dates and intervals preserve precision and reject impossible dates',()=>{const {db,save}=fixture();try{assert.equal(save('a',{composicao:'2012-02'}).data_fim,'2012-02-29');assert.equal(save('b',{composicao:'2011-01-01/2012-03-02'}).data_fim,'2012-03-02');for(const date of ['2011-02-29','2011-13','2020-12-01/2020-01-01','banana'])assert.throws(()=>save('x',{composicao:date}));assert.equal(save('c',{composicao:''}).data_inicio,null);}finally{db.close();}});

test('publication dates, missing required fields and duplicate provenance',()=>{const {db,save}=fixture();try{save('início');for(const patch of [{publicacao:'2011-02-29'},{estado:null},{tags:null}])assert.throws(()=>save('x',{publicacao:'',estado:'Rascunho',tags:[],...patch}));const hash='a'.repeat(64);db.prepare('INSERT INTO fontes VALUES(?,?,?,?)').run(hash,'fontes/'+hash,'original.docx','2026-01-01');save('reimportado',{tags:[]},{fontes:[{hash,inicio:0,fim:3},{hash,inicio:0,fim:3}]});assert.equal(db.prepare('SELECT count(*) AS n FROM versao_fontes').get().n,1);}finally{db.close();}});
